### ISSUE TITLE
Feedback for "Availability"

### ISSUE THREAD

**Issue by ATBECNT** [SAP-docs/cloud-alm-setup-admin-guide#15]
https://help.sap.com/docs/cloud-alm/setup-administration/availability

Correction: EU access available.

**Comment by laura-branitsch** [comment]
Hi @ATBECNT, thank you for your feedback and your patience. I'm checking this internally right now and will get back to you as soon as possible.

**Comment by laura-branitsch** [comment]
Hi @ATBECNT,
Product management confirms that EU access isn't available for SAP Cloud ALM. You can find more information [here](https://help.sap.com/docs/btp/sap-business-technology-platform/regions?version=Cloud#eu-access).
I've now added this link to the documentation. It will be available after the next content update.

If you have further questions regarding EU access in SAP Cloud ALM, feel free to reopen this issue.
