### ISSUE TITLE
Application component responsible for ALM Transport Management is missing

### ISSUE THREAD

**Issue by goreraks** [SAP-docs/cloud-alm-setup-admin-guide#17]
### Issue description

If any help is required or even after transport management is enabled, if there are issues faced while releasing the transport from ALM then the documentation has no information regarding the application component to which a case or OSS message can be raised.

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

Enabling Transport Management

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-alm/setup-administration/transport-management

**Comment by laurabranitsch** [comment]
Hi @goreraks,

Thank you for your feedback! The component for transport management is SV-CLM-IMP-FTR.

We've added this information to the documentation now. The changes will be available with the next content update.

Best regards,
Laura
