### ISSUE TITLE
Change and Deployment Management functionality in CALM

### ISSUE THREAD

**Issue by FundaTas** [SAP-docs/cloud-alm-setup-admin-guide#19]
### Issue description

In videos we see that Change and Deployment Management functionality in CALM is possible for on prem and cloud solutions where in this document it is metioned only for SAP S/4HANA Cloud Public Edition. We would like to clarify which information is up-to-date.

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Supported Solutions

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-alm/setup-administration/supported-solutions

**Comment by laurabranitsch** [comment]
Hi @FundaTas, thanks for reaching out! Can you please let me know which video you're referring to?

The document on SAP Help Portal that you're referring to contains all solutions supported by Change & Deployment Management, not just SAP S/4HANA Cloud Public Edition. Please follow [this link](https://help.sap.com/docs/CloudALM/08879d094f3b4de3ac67832f4a56a6de/3ebab44c25da4cc1997bad08cc00991c?table_nkw_cn3_qkb-capability=Change%20%26%20Deployment%20Management) to see the full list.

**Comment by FundaTas** [comment]
Hi Laura,

I was searching for capability for SAP IBP (SAP Integrated Business Planning for Supply Chain)
as it is also Cloud based tool but I see that it is not supported for Change and Deployment management in CALM.

Thank you very much for clarification.

Best regards
Funda.

**Comment by laurabranitsch** [comment]
Hi @FundaTas, great! Glad I was able to help.
