### ISSUE TITLE
Duplicate Pages: SAP Cloud Transport Management Service

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/cloud-alm-setup-admin-guide#21]
### Issue description

The pages https://help.sap.com/docs/cloud-alm/setup-administration/cloud-transport-management and https://help.sap.com/docs/cloud-alm/setup-administration/sap-cloud-transport-management-service look very similar. I think https://help.sap.com/docs/cloud-alm/setup-administration/sap-cloud-transport-management-service is the more update to date one.

Kind regards,
Sebastian

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

SAP Cloud Transport Management Service

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-alm/setup-administration/cloud-transport-management

**Comment by laurabranitsch** [comment]
Hi @sebastianesch, thank you very much for bringing this to our attention! The structure of the transport management documentation is currently being reworked and it looks like one of the pages was released prematurely. We've rectified the situation now and removed the duplicated pages.
