### ISSUE TITLE
Feedback for "Step 1: Onboard Users in Your Identity Authentication Service"

### ISSUE THREAD

**Issue by jkmaeda** [SAP-docs/cloud-alm-setup-admin-guide#5]
https://help.sap.com/docs/CloudALM/08879d094f3b4de3ac67832f4a56a6de/f2a8a8cd38044f1aae04d8e5491530d4.html?locale=en-US

I would appreciate an easier way to find the template for the file to import users into SAP Cloud ALM via IAS.

**Comment by laura-branitsch** [comment]
Hi @jkmaeda,

Thanks a lot for your feedback! 

Here's the documentation of the Identity Authentication service that deals with the import of users with CSV files: [Import or Update Users for a Specific Application - SAP Help Portal](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/33838e0760f8411daf758a1c11818cc4.html)
It also contains a few examples for the structure of such a CSV file, which you can use to create your own.

I've now added a link it to the setup docs for SAP Cloud ALM:
![image](https://user-images.githubusercontent.com/98023037/166633462-22215f15-d14b-4d91-9f38-862b38c6addb.png)

**Comment by jkmaeda** [comment]
https://people.sap.com/jkmaeda2
