### ISSUE TITLE
Can zoom into picture be linked for the complete picture?

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/cloud-alm-setup-admin-guide#6]
Hello SAP Help Team,

I file this issue here as I've faced it when browsing the page [SAP Cloud Transport Management Service](https://help.sap.com/docs/CloudALM/08879d094f3b4de3ac67832f4a56a6de/730ae36cc6ca419aae747012015cc686.html?locale=en-US). On this page there are several screenshots. There is a little magnification glas with a + in the upper right corner of such screenshots. To see the full size one has to click exactly there:

![Screenshot 2022-06-17 at 08 37 43](https://user-images.githubusercontent.com/2639535/174240032-5e7d1cdc-bdab-4922-843f-4f3d84536fb4.png)
 
I would hope this can be changed and the whole tumbnail can be made clickable. Also it would be great if one can simply switch between all provided screenshots. Just implement it like it is in the SAP Community Blogs: [SAP Cloud ALM Activation](https://blogs.sap.com/2021/11/29/sap-cloud-alm-activation/).

Looking forward for this usability improvement.

Best Regards
Gregor

**Comment by stephaniedaum** [comment]
Hi @gregorwolf, Thanks a lot for the feedback.
Your request definitely makes sense and would be nice to have... but the current behavior is the default in SAP Help Portal. I checked the options to customize this, there's no way at the moment. Let me check with the experts of the infrastructure. The we can get back to you.
Best regards, Steffi

**Comment by gregorwolf** [comment]
https://people.sap.com/gregorw
